name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/setup-go@v2
        name: Set up Go 1.x
        with: 
          go-version: ^1.18
        id: go

      - name: Checkout code into the go module directory
        run: actions/checkout@v2

      - name: Run testing
        run: go test -v -cover ./...